# Generated by Django 5.2.6 on 2025-09-29 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(auto_now=True)),
                ('total_app', models.PositiveSmallIntegerField()),
                ('submitted', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateTimeField(auto_now=True)),
                ('total_app', models.PositiveSmallIntegerField()),
                ('submitted', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('monthapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SUList.monthapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceuser_name', models.CharField(max_length=100)),
                ('references', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('po_num', models.CharField(max_length=10)),
                ('dayapplication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SUList.dayapplication')),
            ],
        ),
    ]
